### ISSUE TITLE
New carousel on frontpage

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/cphtechfest.org#23]
Outstanding tasks:
- [ ] Design
- [ ] Implementation

**Comment by auchenberg** [comment]
@christoffermalling I assume we are skipping this?

**Comment by christoffermalling** [comment]
We'd still like to change it. We just had to figure out how.

Instead of the picture of Robert Scoble with text, we'd like the following:

![header-mockup](https://cloud.githubusercontent.com/assets/20956269/17812105/f1649956-6625-11e6-9c36-4a151082be4f.jpg)

Please use this gif for the wave-image.
![animated-logo_02](https://cloud.githubusercontent.com/assets/20956269/17812130/0c5e5d46-6626-11e6-9153-0b73145b9acd.gif)

Here is the blue text:

"Copenhagen Tech Fest is the one-stop shop to the best of Danish 
technology and startups. +25 events in more than 15 venues 
all over Copenhagen, Sept 1-30.

In other words:"
